services:
  db:
    image: postgres:14
    container_name: yuemnoi-notification
    restart: always
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: notificationdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

volumes:
  postgres_data:
