app_name: user-tokens
port: 8082
DB:
  host: localhost
  port: "5432"
  username: youruser
  password: yourpassword
  database: yourdbname
rabbitmqurl: amqps://fdnesexk:oATQpfEYx_9QHrQjv1O9WftUaOSvheub@octopus.rmq3.cloudamqp.com/fdnesexk
